### PR TITLE
Feature/only keep good data

### PR DESCRIPTION
**Pull request by circlecube**
Before storing data, also check that products and categories response contains key of data, since that's where the content should be and a hiive error returns only a `message` key. 

Also, when the conditions are not met, the method will now return `false` so following processes will exit.

### CODE REVIEW

**Comment by wpscholar** [comment]
@circlecube While this is great, it wouldn't have prevented the issue we saw the other day.

The issue was with the `products` property. The response had a `data` property.

This was the payload we were seeing:

```
{
    "categories": {
        "data": [
            {
                "name": "featured",
                "priority": 100,
                "styles": null,
                "products_count": 6,
                "title": "Featured"
            },
            {
                "name": "services",
                "priority": 10,
                "styles": null,
                "products_count": 11,
                "title": "Services"
            },
            {
                "name": "ecommerce",
                "priority": 9,
                "styles": null,
                "products_count": 13,
                "title": "eCommerce"
            },
            {
                "name": "seo",
                "priority": 5,
                "styles": null,
                "products_count": 5,
                "title": "SEO"
            },
            {
                "name": "security",
                "priority": 3,
                "styles": null,
                "products_count": 6,
                "title": "Security"
            },
            {
                "name": "themes",
                "priority": 0,
                "styles": null,
                "products_count": 12,
                "title": "Themes"
            }
        ],
        "links": {
            "first": "https:\/\/hiive.cloud\/api\/marketplace\/v1\/products\/categories?brand=bluehost&per_page=60&page=1",
            "last": "https:\/\/hiive.cloud\/api\/marketplace\/v1\/products\/categories?brand=bluehost&per_page=60&page=1",
            "prev": null,
            "next": null
        },
        "meta": {
            "current_page": 1,
            "from": 1,
            "last_page": 1,
            "links": [
                {
                    "url": null,
                    "label": "&laquo; Previous",
                    "active": false
                },
                {
                    "url": "https:\/\/hiive.cloud\/api\/marketplace\/v1\/products\/categories?brand=bluehost&per_page=60&page=1",
                    "label": "1",
                    "active": true
                },
                {
                    "url": null,
                    "label": "Next &raquo;",
                    "active": false
                }
            ],
            "path": "https:\/\/hiive.cloud\/api\/marketplace\/v1\/products\/categories",
            "per_page": "60",
            "to": 6,
            "total": 6,
            "ttl": 86400
        }
    },
    "products": {
        "message": "Server Error"
    }
}
```

**Comment by wpscholar** [comment]
Oh, I think these were both separate requests combined into one, right? So your check would apply to the products portion of the request not having a `data` property?

**Comment by wpscholar** [comment]
@circlecube It would be cool if we could define a JSON schema file for the expected responses from the Hiive and then could use those for testing on the Hiive as well as for validation of response data structures on the plugin side. Not sure how feasible that would actually be, but could guarantee that cached responses are always valid.

**Comment by circlecube** [comment]
> @circlecube It would be cool if we could define a JSON schema file for the expected responses from the Hiive and then could use those for testing on the Hiive as well as for validation of response data structures on the plugin side. Not sure how feasible that would actually be, but could guarantee that cached responses are always valid.

I like this idea. Maybe we create a task to help us get there. I don't want to expand this fix too much before getting it out.

**Review by wpscholar — APPROVED** [review]

**Pull request merged**
